/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStorageProvider: typeof import('./src/components/modals/AddStorageProvider.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IJamWriteF: typeof import('~icons/jam/write-f')['default']
    IMaterialSymbolsCloudDownloadOutline: typeof import('~icons/material-symbols/cloud-download-outline')['default']
    IMaterialSymbolsLightDarkModeRounded: typeof import('~icons/material-symbols-light/dark-mode-rounded')['default']
    IMaterialSymbolsLightEditDocumentSharp: typeof import('~icons/material-symbols-light/edit-document-sharp')['default']
    IMaterialSymbolsLightHomeStorageRounded: typeof import('~icons/material-symbols-light/home-storage-rounded')['default']
    IMaterialSymbolsLightLightMode: typeof import('~icons/material-symbols-light/light-mode')['default']
    IMdiAddBox: typeof import('~icons/mdi/add-box')['default']
    IMdiBellRing: typeof import('~icons/mdi/bell-ring')['default']
    IMdiFileDocumentDelete: typeof import('~icons/mdi/file-document-delete')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiLoginVariant: typeof import('~icons/mdi/login-variant')['default']
    IMdiNoteAdd: typeof import('~icons/mdi/note-add')['default']
    IMdiStorage: typeof import('~icons/mdi/storage')['default']
    IMdiTriangleSmallUp: typeof import('~icons/mdi/triangle-small-up')['default']
    LoginPod: typeof import('./src/components/atoms/LoginPod.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PodUrls: typeof import('./src/components/atoms/PodUrls.vue')['default']
    ReadingItem: typeof import('./src/components/ReadingItem.vue')['default']
    ReadingList: typeof import('./src/components/ReadingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShaclAddBookModal: typeof import('./src/components/modals/ShaclAddBookModal.vue')['default']
    ShaclViewBookModal: typeof import('./src/components/modals/ShaclViewBookModal.vue')['default']
    WebId: typeof import('./src/components/atoms/WebId.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
