/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavText: typeof import('bootstrap-vue-next')['BNavText']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    HelloWorld: typeof import('./src/exclude/HelloWorld.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    ICarbonCircle: typeof import('~icons/carbon/circle')['default']
    ICarbonLogin: typeof import('~icons/carbon/login')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IJamWriteF: typeof import('~icons/jam/write-f')['default']
    ILetsIconsColorModeLight: typeof import('~icons/lets-icons/color-mode-light')['default']
    IMaterialSymbolsLightDarkModeRounded: typeof import('~icons/material-symbols-light/dark-mode-rounded')['default']
    IMaterialSymbolsLightLightMode: typeof import('~icons/material-symbols-light/light-mode')['default']
    IMdiBellRing: typeof import('~icons/mdi/bell-ring')['default']
    IMdiDeleteForeverOutline: typeof import('~icons/mdi/delete-forever-outline')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiLoginVariant: typeof import('~icons/mdi/login-variant')['default']
    IMdiNoteAdd: typeof import('~icons/mdi/note-add')['default']
    LoginPod: typeof import('./src/components/LoginPod.vue')['default']
    PodUrls: typeof import('./src/components/PodUrls.vue')['default']
    ReadingList: typeof import('./src/components/ReadingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/unused/TheWelcome.vue')['default']
    WebId: typeof import('./src/components/WebId.vue')['default']
    WelcomeItem: typeof import('./src/components/unused/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
